tutorial_project2/components/urls.py
from django.urls import path

from . import views

app_name = "components"

urlpatterns = [
    path('', views.ComponentCategoryListView.as_view(), name="component_category"),
    path('<int:category>/', views.ComponentListView.as_view(), name="components"),
    path('<int:category>/<int:pk>', views.ComponentDetailView.as_view(), name="component_detail"),
    path('<int:category>/<int:pk>/buy', views.BuyComponentView.as_view(), name="buy_component"),
]

tutorial_project2/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.CoreView.as_view(), name='index'),
]

tutorial_project2/tutorial_project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('components/', include('components.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

tutorial_project2/components/models.py
from django.db import models


class ComponentCategory(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(default='')

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Component(models.Model):
    category = models.ForeignKey(ComponentCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(default='')
    price = models.FloatField(default=0)
    stock = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Component"
        verbose_name_plural = "Components"

    def __str__(self):
        return self.name

tutorial_project2/core/models.py
from django.db import models

# Create your models here.

tutorial_project2/components/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.views.generic import ListView, DetailView, View
from .models import Component, ComponentCategory


# Category view
class ComponentCategoryListView(ListView):
    template_name = 'components/category.html'
    context_object_name = 'categories'

    # Set a query in the models
    def get_queryset(self, *args, **kwargs):
        return ComponentCategory.objects.all()


# Components with a category view, 
class ComponentListView(ListView):
    template_name = 'components/components.html'

    # Set a query in the models
    def get_queryset(self):
        return Component.objects.filter(category_id=int(self.kwargs['category']))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['components'] = self.get_queryset()
        context['category'] = self.kwargs['category']
        return context


# View of details to a specific component
class ComponentDetailView(DetailView):
    model = Component
    template_name = 'components/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["category"] = self.kwargs['category']
        return context
    

# View for buy a component, obtain the id of the component and substracts the number of stock
class BuyComponentView(View):
    def post(self, request, **kwargs):
        info_message = 'An error has ocurred'
        if 'pk' in self.kwargs:
            info_message = 'The purchase has been made successfully.'
            current_component = self.kwargs['pk']
            new_stock = Component.objects.get(id=current_component).stock - 1
            # Component.objects.filter(id=current_component).update(stock=new_stock)
        return HttpResponseRedirect(reverse('components:component_category'))

tutorial_project2/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class CoreView(TemplateView):
    template_name = "core/index.html"

tutorial_project2/components/templates/components/category.html
{% extends 'core/base.html' %}
{% block title_page %}Categories{% endblock %}
{% block body %}
    {% if categories %}
        {% if info_message %}
            <div class="info_block">
                {{ info_message }}
            </div>
        {% endif %}
        <div class="list_section">
            {% for category in categories %}
                <div class="generic_card">
                    <h1>{{ category.name }}</h1>
                    <h4>Description:</h4>
                    <p>{{ category.description }}</p>
                    <a href="{% url 'components:components' category.id %} " class="link_button_1">Search</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No categories available</p>
    {% endif %}
{% endblock %}

tutorial_project2/components/templates/components/components.html
{% extends 'core/base.html' %}
{% if components %}
    {% block title_page %}ComponentsNow{% endblock %}
    {% block body %}
            <div class="list_section">
                {% for component in components %}
                        <div class="generic_card">
                            <h1>{{ component.name }}</h1>
                            <a href="{% url 'components:component_detail' category component.id %}" class="link_button_1">Details</a>
                        </div>
                {% endfor %}
            </div>
    {% endblock %}
{% else %}
    <p>This category of components is not available at the moment</p>
    {{ category }}
{% endif %}

tutorial_project2/components/templates/components/detail.html
{% extends 'core/base.html' %}
{% if component %}
{% block title_page %}ComponentsNow | {{ component.name }}{% endblock %}
{% block body %}
<div class="detail_block">
    <div class="detail_image_block">
        <img src="" alt="">
    </div>
    <h1>{{ component.name }}</h1>
    <hr>
    <h3>Description</h3>
    <p>{{ component.description }}</p>
    <hr>
    <ul>
        <li>Price: ${{ component.price }}</li>
        <li>Stock: {{ component.stock }}</li>
    </ul>
    <hr>
    <form action="{% url 'components:buy_component' category component.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Buy" class="link_button_1_fluid">
    </form>
</div>
{% endblock %}
{% else %}
<p>This component has not been found</p>
{% endif %}

tutorial_project2/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title_page %}ComponentsNow{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}" />
</head>
<body>
    {% include "core/nav.html" %}
    <section>
    {% block body %}
    {% endblock %}
    </section>
    {% comment %}{% include "core/footer.html" %} {% endcomment %}
</body>
</html>

tutorial_project2/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title_page %}Home{% endblock %}
{% block body %}
<div class="list_section">
<h1>ComponentsNow</h1>
<p>{% lorem 7 p random %}</p>
</div>
{% endblock %}

tutorial_project2/core/templates/core/nav.html
<header>
    <nav>
        <ul>
            <li class="nav-title"><h3>ComponentsNow</h3></li>
            <li><a href="{% url 'core:index' %}">Home</a></li>
            <li><a href="{% url 'components:component_category' %}">Components</a></li>
            {% comment %}<li><a href="{% url 'core:contact' %}">Contact</a></li>{% endcomment %}
        </ul>
    </nav>
</header>