api_django/api_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('computers/', include('computers.urls')),
    path('admin/', admin.site.urls),
]

api_django/computers/urls.py
from django.urls import path

from . import views

app_name = 'computers'

urlpatterns = [
    path('',views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

api_django/computers/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

api_django/computers/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
#from django.template import loader
from .models import Question, Choice
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'computers/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'computers/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'computers/results.html'

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     #template = loader.get_template('computers/index.html')
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'computers/index.html', context)

# We used Http404 for print a custom 404 error, in this case we use the get_object_404 shorcut method,
# that combine the Http404 exception and the Model.objects.get() method


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'computers/detail.html', {'question': question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'computers/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'computers/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('computers:results', args=(question.id,)))

api_django/computers/templates/computers/detail.html
<h1>{{ question.question_text}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'computers:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        {% comment %} forloop.counter display the actual number of iterations in the loop {% endcomment %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    {% endfor %}
    <br>
    <input type="submit" value="Vote">
</form>

api_django/computers/templates/computers/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        {% comment %} The url label go to an espeficic url defined in urls.py it gets the variable "name" {% endcomment %}
        {% comment %} We can set a namespace if you have urls with the same name in many applications, you need 
        to set a namespace to especify what template do you want{% endcomment %}
        <li><a href="{% url 'computers:detail' question.id%}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No computers are avaliable.</p>
{% endif %}

api_django/computers/templates/computers/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        {% comment %} {{ value|pluralize }} Pluralizes a word if the value is more than 1 {% endcomment %}
        <li><h2>{{ choice.choice_text }}</h3></li>
        <li><h3>vote{{ choice.votes|pluralize }}: {{ choice.votes }}</h3></li>
    {% endfor %}
</ul>

<a href="{% url 'computers:detail' question.id %}">Vote again?</a>